version: 0.0
os: linux
files:
  - source: /target/release
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: aws/build.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: aws/start_app.sh
  ApplicationStop:
    - location: aws/stop_app.sh