version: 0.0
os: linux
files:
  - source: /aws
    destination: /home/ec2-user/app/scripts
hooks:
  AfterInstall:
    - location: aws/after-install.sh
  ApplicationStart:
    - location: aws/start-app.sh
  ApplicationStop:
    - location: aws/stop-app.sh