name: rust-ci-main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - run: rustup component add clippy
    - name: build
      run: cargo build --verbose
    - name: lint
      run: cargo clippy --all-targets --all-features
    - name: tests
      run: cargo test --verbose
  
  coverage:
    needs: build-lint-test
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v3

      - name: Generate coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --out Lcov
      - name: Push coverage
        run: coverallsapp/github-action@v2.2.3
            
